/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2011 Hex-Rays <info@hex-rays.com>

   Detected compiler: Unknown
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Data declarations


//-------------------------------------------------------------------------
// Function declarations



// ALL OK, 0 function(s) have been successfully decompiled
